[package]
name = "pyrite_box"
version = "0.1.0"
edition = "2018"

#[profile.dev]
#opt-level = 1

[dependencies]
bevy = "0.5"
bevy_egui = "0.8.0"
bracket-random = "0.8"
serde = "1.0"
ron = "0.7"
anyhow = "1.0.51"
